### ISSUE TITLE
convention for specifying browser support

### ISSUE THREAD

**Issue by MartinMalinda** [ember-cli/rfcs#103]
Currently both autoprefixer and babel can take a browser support params which determine what kind of polyfills need to be included.

I think it could be useful to have browserSupport property by default in `config.js` which could then be read both by babel and autoprefixer.

Potentionally even Ember-CLI could then filter out certain code based on the browser support (Ember.RSVP ?).

**Comment by rwjblue** [comment]
Good news, this has already been implemented and is available in the latest beta release! 🎉 

Some links for reading through details:

* https://github.com/ember-cli/rfcs/blob/master/complete/0095-standardise-targets.md
* http://emberjs.com/blog/2017/03/19/ember-2-12-released.html#toc_targets
* http://emberjs.com/blog/2017/03/19/ember-2-12-released.html#toc_babel-6
* https://github.com/kimroen/ember-cli-autoprefixer/issues/32
* https://github.com/ember-cli/ember-cli-eslint/issues/158

**Comment by MartinMalinda** [comment]
That's great! I should have checked first.
