### ISSUE TITLE
Dropping ember data from the default blueprint

### ISSUE THREAD

**Issue by piotrpalek** [ember-cli/rfcs#115]
Hey, first of all if this has been discussed anywhere before just point me to it, I didn't find any topic like this anywhere.

So this is just a thought I've been having for some time now, but what would the general consensus be with regards to removing ember data from the default ember-cli blueprints?
It seems to me that this would give us a big benefit in terms of **significantly** less overhead for newcomers (if we also move ED out of the tutorial/guides and into a separate "advanced" or "managing data" section) while practically speaking being a non-issue for advanced people (one ember install away from adding it).

Are there some big issues I'm missing? It seems to me like removing it would be of more value then leaving it in. I would like to see more people adopting Ember, but I feel like our onboarding process has much room for improvement. This way would be a quick (and unless I'm missing something pretty painless) way to shed much of the perceived weight of Ember without impacting experienced users.

:+1:  / :-1: / :rage4: ?

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
