### ISSUE TITLE
addon entry-point other than index.js

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/rfcs#122]
### Summary

I would like to create a library that is pure JS at its core, but is consumable as an Ember addon. I can use the `main` option in `package.json` to specify an entry point other than `index.js`, but that entry-point is both for pure-JS (e.g. node) consumption and Ember-CLI consumption.

### Use-Case

As teams grow, it is often helpful to extract code from one application into a shared library. It's easy to do that as an Ember addon. But not all teams and projects use Ember.

Currently, the "standard" solution is to have two packages: `@my-org/foo` and `@my-org/ember-foo`. The former contains the business logic of the addon. The latter contains little more than an `index.js` with some Broccoli tree management to support `import foo from '@my-org/foo'` in an Ember application. The extra package means more time managing dependencies.

It would be much easier to maintain a single package that is usable without ember, but which knows how to package itself for ember.

### Implementation Idea

```js
// package.json
"ember-addon": {
  "main": "lib/ember-addon.js"
},
"optionalDependencies": {
  // things lib/ember-addon.js uses directly:
  "broccoli-merge-trees": "^2.0.0 || ^3.0.0",
  "ember-cli-babel": ">= 6.0.0",

  // ember compatibility:
  "ember-source": "^2.8.0 || ^3.0.0"
}
```

### References

* #110
* [EmberCLI: extending](https://ember-cli.com/extending/#packagejson)

**Comment by rwjblue** [comment]
I don’t fully understand. The exact suggestion that you made actually does work (and has for a long time), are you saying that we should do that by default, something else?

**Comment by jamesarosen** [comment]
> The exact suggestion that you made actually does work

Oh! Is it documented somewhere? I read through the [extending](https://ember-cli.com/extending/#packagejson) docs. They discuss using the `main` property, but not `ember-addon.main`.

**Comment by buschtoens** [comment]
There is also ember-auto-import, which allows you to import any standard JS lib.

**Comment by jamesarosen** [comment]
Authoring a pure-JS module and using ember-auto-import is a great start.

One thing that I'd like to be able to do is export a function for pure-JS users and that same function wrapped in a Helper for Ember users:

```js
// addon/my-function.js
export default function(…) { … }

// addon/helpers/my-function.js
import { helper } from '@ember/component/helper'
import myFunction from '../my-function'

export default helper(myFunction)

// index.js
export default {
  myFunction: require('./addon/my-function')
}

// ember-addon.js
export default {
  name: 'my-package'
}
```

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
