### ISSUE TITLE
Public API to examine app dependencies from an addon

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/rfcs#123]
In an addon I can look in `project.packageInfoCache.entries` and see all of the installed packages at app build time, but as @Turbo87 mentions in https://github.com/ivanvanderbyl/ember-d3/pull/69#pullrequestreview-194349135 this doesn't appear to be public. 

In addons like `ember-d3` or `@fortawesome/ember-fontawesome` where it is important to validate or transform packages at build time this is needed functionality.

The private method https://ember-cli.com/api/classes/Project.html#method_dependencies exposes this, but only at the level of the application not the deep tree present in `project.packageInfoCache.entries`.

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. Would you mind migrating this issue over to emberjs/rfcs?

**Comment by jrjohnson** [comment]
No problem. I created: https://github.com/emberjs/rfcs/issues/436

**Comment by rwjblue** [comment]
Thank you!
