### ISSUE TITLE
Feature request: Option to add directory to be watched for automatic server restart

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/rfcs#25]
I'd like to add directories (that contain some magic used by an addon) to the watcher, so that changed files trigger a server restart (like app, tests etc.). Ideally this could be done by said addon through a hook.

Use case: I use this to provide some extended version of mocks (like `server` directory, only in a different directory).

This was originally reported as https://github.com/ember-cli/ember-cli/issues/4717.

**Comment by stefanpenner** [comment]
so something like:

``` js
server.watchedPaths.push('config/foo.js')
server.watchedPaths.push('other-folder/{some/glob}.js')
```

I would also like to combine the server restart and broccoli rebuild watching more closely. This way we don't end up with overlapping watch logic.

In addition, restarting the whole process if the brocfile changes would be great...

**Comment by jnfingerle** [comment]
Sounds great :-)

**Comment by shwoodard** [comment]
+1

I need to be able to drop a js file into my config dir with an es6 module exported object at deploy time.  Would be nice to be able to inject it in an initializer but I cannot import it atm.

**Comment by stefanpenner** [comment]
@shwoodard that sounds pretty much unrelated to this request

**Comment by shwoodard** [comment]
@stefanpenner not only are you correct, but it is also nonsense what I said because at deploy time the es6 would already be transpiled so the whole concept doesn't make sense.  Once again, I feel stupid...hahaha.

**Comment by stefanpenner** [comment]
I still think this is a good idea, if someone is interested they are welcome to prepare a more detailed RFC. This will allow us to hash out the details before implementing.

That being said, keeping an idle issue around doesn't seem like much value.

**Comment by jesseditson** [comment]
I've rebooted the spirit of this RFC here: https://github.com/ember-cli/rfcs/issues/81, as I ran across this issue in my ember setup.
