### ISSUE TITLE
Deploy existing build to different target.

### ISSUE THREAD

**Issue by theazureshadow** [ember-cli/rfcs#27]
One of our project goals is to separate build types (e.g. debug, production) from deployment targets (e.g. development, alpha, production). Ideally in our build phase we run all build types, then reuse those built artifacts for any given deployment target. Here are some benefits of this approach:
- We have confidence that the artifact we build and test is the same as the artifact we deploy. We have seen irresponsible NPM dependency changes break deploys after a successful build.
- When we promote a build to prod, we know the build and test was as close as possible to the build we have validated in an earlier stage.
- We can deploy old artifacts to a new target. For example, I may want to bring up a new server to test a particular feature branch or run a demo, or we may add another stage in our CI pipeline.
- We can quickly deploy without requiring a build/test phase. This is very important for things like rollback or deploying hotfixes.

Here is a rough description of the build / deploy flow we want to implement:

Build:
1. For each build type, create the artifact using `ember build --environment $type`.
2. After each build, bundle the `dist` folder as a tar artifact.
3. Upload each of those artifacts to s3, e.g. `aws s3 cp $type.tar s3://my-app-builds/$commit/$type.tar`

Deploy:
1. Download the desired artifact from s3 and untar.
2. Add target-specific config, possibly using an Ember CLI command: `ember target --folder dist --config production.json`
3. Deploy the ember application to a web server, or as an s3 static website.

I was going to add this use case as a comment on ember-cli/rfcs#26, but it seemed different enough to warrant its own issue. The important difference is that this very deliberately doesn't require any changes in the build for a different target.

**Comment by stefanpenner** [comment]
the seems to describe some process after `ember build --env production --target s3` has run. I am unclear if this is in-scope for ember-cli or part of the ember-deploy project. Initially I am inclined to think not, and this should be part of the ember deploy effort. If there are missing parts of ember-cli's build process, like my #26, then that needs to be enumerated.

**Comment by theazureshadow** [comment]
@stefanpenner: Thanks pointing me at that project. I'll close this here and open new issues if there are missing pieces.
