### ISSUE TITLE
`ember install` rework.

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/rfcs#34]
See https://github.com/ember-cli/ember-cli/issues/3163

**Comment by stefanpenner** [comment]
Ya, eventually I would like to offer this. I am hoping to offer sometime after we drop bower, and when we work to improve peerDeps of ember-addons in npm.

That way we can offer this feature without trollage.

**Comment by jakehow** [comment]
@stefanpenner what blocks dropping bower currently?

**Comment by jakehow** [comment]
@stefanpenner nevermind, just found https://github.com/ember-cli/rfcs/issues/41

I was looking in emberjs/rfcs

**Comment by stefanpenner** [comment]
also to follow up, to get uninstall right we need to actually flesh out install.

TL;DR `install/uninstall` JJ-abrams style exploration is required.

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
