### ISSUE TITLE
--watcher=none to disable watching all-together

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/rfcs#42]
seems to be coming up from time to time, seems like we could quite easily support it. Obviously needs fleshing out.

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
