### ISSUE TITLE
Daemon process for faster startup

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/rfcs#54]
Ember CLI currently has a quite high startup time due to the over 2000 `require()` calls and potentially more in every addon and blueprint in the projects. Gradle in the Java world had roughly similar problems and solved them by using a long-lived [daemon process](https://docs.gradle.org/current/userguide/gradle_daemon.html) that is controlled by their `gradle` CLI tool.

Speeding up the startup time is required for things like #23 but I admit that I'm not sure yet if the added complexity is worth it. It would likely need to have a few more advantages to justify it. #4 might also be related to this idea.

**Comment by stefanpenner** [comment]
This is a good idea, that being said the startup time being less then 400 or 500ms is a reasonable expectation, if it is not something else might be funk

**Comment by locks** [comment]
In due time :P
