### ISSUE TITLE
Automatically fill repository field

### ISSUE THREAD

**Issue by leo** [ember-cli/rfcs#58]
When generating a new `package.json` using `npm init`, the "repository" field automatically gets filled if the destination directory is a git repository and has a remote configured.

However, when runing `ember init` within a repo's directory, the "repository" field currently simply stays empty. Wouldn't it be great if ember-cli did the same thing?
## Suggestion

Currently, npm isn't really doing a great job because it fills the field with an object containing several things like the type of the repo and the url:

``` json
"repository": {
  "type": "git",
  "url": "https://github.com/ember-cli/rfcs.git"
}
```

However, the upper code isn't needed when it comes to GitHub repositories. Instead of that, ember-cli should do it like this ([here](https://docs.npmjs.com/files/package.json#repository) are other shorthand examples for different providers):

``` json
"repository": "ember-cli/rfcs"
```

**Comment by nathanhammond** [comment]
Notes:
- Most people run `ember new` to get their first generated blueprint. By the time they rerun `ember init` six weeks later they will have hopefully already set a repository value inside of their application or addon. (`ember new` will never have a remote.)

Concerns:
- Most people won't encounter this until well past the time it matters.
- This _removes_ clarity about where exactly the repository is hosted. I will always prefer specific and complete over needing to know the implementation details.
- I'm generally opposed to "surprising" behavior, which is what I would consider this to be. `ember init` as of now doesn't include any logic and this would be a departure from that approach. I'm not sure that it's possible to capture the repository field at a reasonable time in the process to make it "unsurprising."

**Comment by leo** [comment]
👍
