### ISSUE TITLE
Provide a way to skip import of add-on assets

### ISSUE THREAD

**Issue by felixbuenemann** [ember-cli/rfcs#69]
There is currently no clean way to skip the import of assets triggered by an ember-cli addon from inside the ember app.

In some cases files can be removed by passing a broccoli `Funnel` to `app.toTree()` or post-processing the generated tree using a funnel.

However this doesn't work for the very common case, where an ember-cli addon adds a default style, for example from a wrapped bower package, because all css is already concatenated into addons.css when we get the change to process the tree.

It would be great if ember-cli provided a funnel that gets executed before any concatenation or preprocessing of imported trees is done, which could then be used to exclude (or include) additional files using the patterns provided by broccoli-funnel.

**Example:**

The addon `ember-foo` wraps the bower package `foo` and imports its assets in the `included()` hook:

``` javascript
module.exports = {
  name: 'ember-foo',

  included: function(app) {
    app.import(app.bowerDirectory + '/foo/foo.js');
    app.import(app.bowerDirectory + '/foo/foo.css');
  }
};
```

We do not need the file `foo.css`because we have provided our own styles and overriding the existing styles would be cumbersome, so it would be great if we could exclude it in `ember-cli-build.js`:

``` javascript
var app = new EmberApp(defaults, {
  filterAddonTree: {
    exclude: ['bower_components/foo/foo.css']
  }
});
```

In a similar fashion it is also possible, that a bower component has multiple variants and we want to `exclude: ['bower_components/foo/foo-deluxe.js']` and `include: ['bower_components/foo/foo-light.js']` because it is sufficient for our needs.

Both of the above mentioned examples could be solved by adding additional configuration to the `ember-foo` addon, but it would be great if there was a simple way to solve such a common issue without having to modify the addon to provide every possible permutation of assets.

**Comment by kellyselden** [comment]
https://github.com/kellyselden/ember-cli-funnel was created to solve this problem, although it would need to be extended to support css as well as javascript.

**Comment by felixbuenemann** [comment]
@kellyselden It might be possible to solve this using an addon by implementing the `preprocessTree` hook, which runs before preprocessors. ember-cli-funnel currently wraps the `EmberApp#appAndDependencies` method, which runs after template and js preprocessing…

**Comment by felixbuenemann** [comment]
OK, `preprocessTree` doesn't currently work for excluding files, it will crash with `ENOENT` for the excluded files during `SimpleConcat: Concat: Vendor Styles/assets/vendor.css`.

**Comment by nathanhammond** [comment]
So, this is actually a known issue and we want to _extract_ the default Ember CLI CSS handling into an addon itself and then add it back in via whatever (possibly new) public APIs that it needs.

There are likely a few more hooks that we need and we'll identify those as part of this process. Check out our core team meeting notes from the last two weeks:
- https://github.com/emberjs/core-notes/pull/108
- https://github.com/emberjs/core-notes/pull/109

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
