### ISSUE TITLE
Breaking "bugfixes" for an eventual 3.0

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/rfcs#72]
These are things that are very much broken but we can't change for reasons of backwards compatibility. This list is for a _very_ specific category of issue. These should tend toward mechanical changes.

When you comment on this thread please identify _why_ your issue fits this category. The canonical list will be hoisted here. Comments will only be used to identify which things should be promoted to this top post.
- [ ] [Stop defining globals in `vendor-prefix.js`.](https://github.com/ember-cli/ember-cli/issues/6351)
- [ ] Remove [`deprecateUI`](https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/utilities/deprecate.js) (Standard deprecation removal.)

**Comment by kellyselden** [comment]
remove https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/utilities/deprecate.js

normal deprecation removal.
