### ISSUE TITLE
Access to `app.options` is inconsistent

### ISSUE THREAD

**Issue by zackthehuman** [ember-cli/rfcs#73]
Access to the build-time configuration (`app.options`) is inconsistent between the public hooks in an addon. For instance, `this.app` is `undefined` inside of `setupPreprocessorRegistry` but not inside of `included`.

This inconsistency makes things that should be straightforward more difficult. To illustrate:

```
included: function (app) {
  console.log('included', !!this.app);
}

setupPreprocessorRegistry: function(type, registry) {
  console.log('setupPreprocessorRegistry', !!this.app);
}
```

Logs the following:

```
setupPreprocessorRegistry false
setupPreprocessorRegistry false
included true
```

However, the `app` _is actually available_ if you look in the "right" place:

```
setupPreprocessorRegistry: function(type, registry) {
    console.log('setupPreprocessorRegistry', type, !!registry.app);
}
```

Logs:

```
setupPreprocessorRegistry self true
setupPreprocessorRegistry parent true
```

So it is clear that the information is _available_ before `included` is called, it just isn't exposed to the addon directly. There are ways to work around it -- for instance by stashing the parent's `registry` and then using it inside of `included` to add preprocessors -- but then what is the point of having a separate hook?

Another workaround is to put all this configuration inside of `environment.js` and then accessing it via the `project` config. This is even worse because all of that stuff ends up in the client when it is only needed at build time. This is just terrible, but many people do it.

There are definitely valid use cases for reading the build configuration from within `setupPreprocessorRegistry`, namely:
- compilation settings for CSS preprocessors
- settings for things that have template transforms

Ultimately, this particular flaw causes developers to introduce temporal coupling into their addon by ensuring that parts of their code _only run_ after `included` in order to assure `this.app` is a thing. This is bad, and unnecessary since it can be proven that the information is already there to begin with.

**Comment by stefanpenner** [comment]
ember-cli/ember-cli#7059 may resolve this?

**Comment by zackthehuman** [comment]
It looks promising. My ugly hacks to work around this are still going strong so it would be great to get rid of them!

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
