### ISSUE TITLE
Configurable paths for Tree Paths

### ISSUE THREAD

**Issue by jasonmit** [ember-cli/rfcs#78]
Currently, all tree paths (`app`, `tests`, `vendor`, etc.) are static and cannot be configured.

I'd like to propose adding `inputPaths` to the `EmberApp` options hash allowing them to be optionally configured.

```js
const app = new EmberApp(defaults, {
  inputPaths: {
    vendor: 'statics/vendor',
    public: 'statics/public',
    // etc..
  }
});
```

Unsure if this is a large enough change to warrant an RFC or not.  Happy to PR this if it's something that has buy in.

**Comment by rwjblue** [comment]
Hmm. It surprises me that these are perceived as static. They should be already configurable via `trees` option.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L218-L251

**Comment by jasonmit** [comment]
Er, bad use of words.

I wasn't sure if this was a public API and it requires more intimate knowledge than I think most people are use to (returning broccoli trees versus providing paths).

**Comment by jasonmit** [comment]
I'm going to close this now, feel free to reopen if `trees` is private and I can do what is necessary to make it public (update docs or introduce inputPaths).

Thanks @rwjblue

**Comment by nathanhammond** [comment]
They're public enough that they won't change until we write `ember-modules-app`.
