### ISSUE TITLE
Expose API to customize and/or disable colors used in terminal output.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/rfcs#83]
This has a number of use cases, but I'll list just a couple:

* Users with various visual impairments may not be able to see all colors (e.g. folks with red/green color blindness may not be able to see or differentiate the `chalk.red` colored output).
* Colors that we use by default may conflict with terminal settings (e.g. mocha's default colors conflicted with solarized dark theme such that the test name output was completely invisible).
* Some terminals / CI systems / etc do not properly force `chalk` to opt out of colored output (resulting in bizarro text output).

Suggestions: 

* Allow customization of specific colors in `.ember-cli` file.  I _believe_ this is possible but it needs research.
* Document support for `--no-color` command line flag on all commands (this is already supported by way of https://github.com/chalk/supports-color, but isn't documented at all)

**Comment by stefanpenner** [comment]
> Document support for --no-color command line flag on all commands (this is already supported by way of https://github.com/chalk/supports-color, but isn't documented at all)

it will also warn when parsed by our command parser, as non of our commands support this. 

Ideas:

* add this to our commands  or treat it like `--silent` a global modifier
* make it so that setting `.ember-cli` file correctly informs chalk
