### ISSUE TITLE
Don't set license in app's package.json

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/rfcs#87]
`ember g license <license-type=MIT>`? Makes it relatively straightforward to toggle off and on, simple to chain to a previous blueprint, provides a choke point for the configuration. And then we can start to make it configurable.

Slightly odd `ember d license` invocation: it doesn't matter what the type so it doesn't have to be parallel with the `generate` command.

That we assume a license at all is probably bad.

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?
