### ISSUE TITLE
Support in-repo commands by default.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/rfcs#94]
Today, if you would like to add a command you must add an in-repo addon that implements the `includedCommands` method.

Contrast this with the ease of making a built-in blueprint: simply place a file in `blueprints/some-name/index.js` and 💥 everything works.

This issue is mostly to gauge interest in supporting auto-detection of project and addon commands by way of a specific location on disk (e.g. `<project-root>/commands` or `<project-root>/lib/commands`)...

👍 / 👎 ?

**Comment by nathanhammond** [comment]
Squatting on a folder is something I'm not a huge fan of, but this is a pretty common scenario and we have precedent. Consider this a mild :+1:.

**Comment by kellyselden** [comment]
Couldn't have said it better than @nathanhammond. Big yes to first class support. Bikeshedding on folder API necessary though IMO.

**Comment by trentmwillis** [comment]
I'm :+1: on this. Though, if we opt for a non-root folder, then we should likely consider updating the structure for blueprints as well (IMO).
